spring.application.name=userauth

#Postgres
spring.datasource.url=jdbc:postgresql://localhost:5432/auth_db
spring.datasource.username=postgres
spring.datasource.password=root

#Logs in console
logging.level.org.springframework.web=DEBUG

#Mail verification - mailtrap.io sandbox
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=383b6578f9f3c4
spring.mail.password=639cfa4bd2a9f8
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true